Mission09_vim12/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_vim12.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_vim12.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent (Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Mission09_vim12/Components/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_vim12.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_vim12.Components
{
    public class CategoriesViewComponent :ViewComponent
    {
        //Get data for component
        private IBookstoreRepository repo { get; set; }

        public CategoriesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }
        //Get unique categories to filter by
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];
            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return View(categories);
        }
    }
}

Mission09_vim12/Views/Shared/BookSummary.cshtml
@{
}
@model Book
<!--Partial view for Index page-->
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>
            @Model.Title
            <span class="badge bg-success" style="float:right">
                <small>Price: @Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">
        <ul>
            <li>Author: @Model.Author</li>
            <li>Publisher: @Model.Publisher</li>
            <li>ISBN: @Model.Isbn</li>
            <li>Classification: @Model.Classification</li>
            <li>Category: @Model.Category</li>
            <li>Number of Pages: @Model.PageCount</li>
        </ul>

    </div>
    <!--Make a path to the buy page for each book-->
    <form method="post" asp-page="/Buy">
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-right">Buy</button>
        </span>
    </form>
</div>

Mission09_vim12/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bookstore Galore</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-info text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Bookstore Galore</div>
                <div class="col-6 text-right">
                    <vc:cart-summary></vc:cart-summary>
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:categories></vc:categories>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>