Mission09_vim12/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_vim12.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_vim12.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Cart cart { get; set; }
        //constructor to pass databsae info
        public PurchaseController(IPurchaseRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }
        //Info for purchase/checkout
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }
        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");

            }
            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchase(purchase);
                cart.ClearCart();
                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }

        }

    }
}

Mission09_vim12/Pages/Buy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission09_vim12.Infrastructure;
using Mission09_vim12.Models;

namespace Mission09_vim12.Pages
{
    public class BuyModel : PageModel
    {
        //build instance of database
        private IBookstoreRepository repo { get; set; }
        public BuyModel(IBookstoreRepository temp,Cart c)
        {
            repo = temp;
            cart = c;
        }
        public Cart cart { get; set; }
        //get the url so the user can return to the page they were on before the cart
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);
            
            //initialize cart
            cart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage ( new {ReturnUrl = returnUrl});
        }
    }
}

Mission09_vim12/Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mission09_vim12.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Mission09_vim12/Pages/Buy.cshtml
@page
@model Mission09_vim12.Pages.BuyModel
@{
}
<h2>Your Cart</h2>

<table class="table table-bordered table-striped">
    <thead class="table-info">
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model.cart.Items) { 
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@((i.Book.Price).ToString("c"))</td>
                <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>
                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot class="table-info">
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>
<div>
    <a class="btn btn-info" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-info" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

Mission09_vim12/Pages/PurchaseCompleted.cshtml
@page
@model Mission09_vim12.Pages.PurchaseCompletedModel
@{
}

<div class="text-center">
    <h2>Thanks! Your order has been confirmed.</h2>
    <a class="btn btn-info" asp-controller="Home">Return Home</a>
</div>

Mission09_vim12/Pages/_BuyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-info text-white p-2">

        <span class="navbar-brand ml-2">BookStore Galore</span>

    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>